package com.fulfilltrack.FulfillTrack.auth.permisos;

public enum Permisos {
    // Empresas
    VER_EMPRESAS, CREAR_EMPRESA, ACTUALIZAR_EMPRESA, DESACTIVAR_EMPRESA,

    // Depósitos
    VER_DEPOSITOS, CREAR_DEPOSITO, ACTUALIZAR_DEPOSITO, DESACTIVAR_DEPOSITO,

    // Productos
    VER_PRODUCTOS, VER_PRODUCTOS_EMPRESA, CREAR_PRODUCTO, ACTUALIZAR_PRODUCTO, DESACTIVAR_PRODUCTO,

    // Stock
    VER_STOCK, GESTIONAR_STOCK,

    // Pedidos
    VER_PEDIDOS, CREAR_PEDIDO, ACTUALIZAR_ESTADO_PEDIDO,

    // Despachos
    VER_DESPACHOS, CREAR_DESPACHO,

    // Liquidaciones
    VER_LIQUIDACIONES, CREAR_LIQUIDACION,

    // Usuarios / empleados
    VER_USUARIOS, CREAR_USUARIO, ACTUALIZAR_USUARIO, DESACTIVAR_USUARIO
}
